apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: goormthon-4 #FIXME:

resources:
    - backend.yaml
    - ingress.yaml

configMapGenerator:
    - name: backend-config
      files:
          - config.json=config/backend-config.json

generatorOptions:
    disableNameSuffixHash: true
